name: dominikw
favicon: null
layout_spectrum: 0.09171712468378246
typography_spectrum: 0.47566695255227387
title: Random photos from Pentax 645Z
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#465a75'
    - '#cfdcee'
    - '#9ab2ce'
    - '#695400'
    - '#e5c053'
  brandStrength: 0.1875
  lightness: 0.1918100486509502
  saturation: 0.2669363678433001
  rhythmicContrast: 0.6563839062582701
purpose: []
